# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcde8248a6aa39244ccf6b3f08661b1188166026bae97ff5708d48097083c8d05556e5da263afbdce544d3cabd7bd1565b1959d3ff23a38360139c3d1c07dd56

test:
  secret_key_base: 5680a59acb0f03aafa0d1bbe67ae20f25b9c29f550d863d3d1d4219ea2eca7ea38517856e6149bcded363122ce7e05245b2df58a5291b6ae7e9d1c0259c7d0a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
